openapi: 3.2.0
info:
  title: Upsun.com Rest Environment Backups API
  version: '1.0'
  contact:
    name: Support
    url: https://upsun.com/contact-us/
  termsOfService: https://upsun.com/trust-center/legal/tos/
  description: '# Introduction


    Upsun, formerly Platform.sh, is a container-based Platform-as-a-Service.'
  x-logo:
    url: https://docs.upsun.com/images/upsun-api.svg
    href: https://upsun.com/#section/Introduction
    altText: Upsun logo
servers:
- url: '{schemes}://api.upsun.com'
  description: The Upsun.com API gateway
  variables:
    schemes:
      default: https
security:
- OAuth2: []
tags:
- name: Environment Backups
  description: 'A snapshot is a complete backup of an environment, including all the

    persistent data from all services running in an environment and all

    files present in mounted volumes.


    These endpoints can be used to trigger the creation of new backups,

    get information about existing backups, delete existing backups or

    restore a backup.

    More information about backups can be found in our

    documentation.'
paths:
  /projects/{projectId}/environments/{environmentId}/backup:
    post:
      parameters:
      - in: path
        required: true
        schema:
          type: string
        name: projectId
      - in: path
        required: true
        schema:
          type: string
        name: environmentId
      operationId: backup-environment
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentBackupInput'
      tags:
      - Environment Backups
      summary: Create backup of environment
      description: 'Trigger a new backup of an environment to be created. See the

        Backups

        section of the documentation for more information.'
  /projects/{projectId}/environments/{environmentId}/backups:
    get:
      parameters:
      - in: path
        required: true
        schema:
          type: string
        name: projectId
      - in: path
        required: true
        schema:
          type: string
        name: environmentId
      operationId: list-projects-environments-backups
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackupCollection'
      tags:
      - Environment Backups
      summary: Get an environment's backup list
      description: Retrieve a list of objects representing backups of this environment.
      x-stability: EXPERIMENTAL
  /projects/{projectId}/environments/{environmentId}/backups/{backupId}:
    get:
      parameters:
      - in: path
        required: true
        schema:
          type: string
        name: projectId
      - in: path
        required: true
        schema:
          type: string
        name: environmentId
      - in: path
        required: true
        schema:
          type: string
        name: backupId
      operationId: get-projects-environments-backups
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Backup'
      tags:
      - Environment Backups
      summary: Get an environment backup's info
      description: 'Get the details of a specific backup from an environment using the `id`

        of the entry retrieved by the

        Get backups list

        endpoint.'
      x-stability: EXPERIMENTAL
    delete:
      parameters:
      - in: path
        required: true
        schema:
          type: string
        name: projectId
      - in: path
        required: true
        schema:
          type: string
        name: environmentId
      - in: path
        required: true
        schema:
          type: string
        name: backupId
      operationId: delete-projects-environments-backups
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
      tags:
      - Environment Backups
      summary: Delete an environment backup
      description: 'Delete a specific backup from an environment using the `id`

        of the entry retrieved by the

        Get backups list

        endpoint.'
      x-stability: EXPERIMENTAL
  /projects/{projectId}/environments/{environmentId}/backups/{backupId}/restore:
    post:
      parameters:
      - in: path
        required: true
        schema:
          type: string
        name: projectId
      - in: path
        required: true
        schema:
          type: string
        name: environmentId
      - in: path
        required: true
        schema:
          type: string
        name: backupId
      operationId: restore-backup
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentRestoreInput'
      tags:
      - Environment Backups
      summary: Restore an environment snapshot
      description: 'Restore a specific backup from an environment using the `id`

        of the entry retrieved by the

        Get backups list

        endpoint.'
      x-stability: EXPERIMENTAL
components:
  schemas:
    EnvironmentRestoreInput:
      type: object
      properties:
        environment_name:
          type:
          - string
          - 'null'
          title: Environment name
          description: ''
        branch_from:
          type:
          - string
          - 'null'
          title: Branch from
          description: ''
        restore_code:
          type: boolean
          title: Is code or data restored
          description: Whether we should restore the code or only the data
        restore_resources:
          type: boolean
          title: Is resources restored
          description: Whether we should restore resources configuration from the backup
        resources:
          type:
          - object
          - 'null'
          properties:
            init:
              type:
              - string
              - 'null'
              enum:
              - backup
              - default
              - minimum
              - parent
              title: Init Resources
              description: The resources used when initializing services of the environment
          required:
          - init
          additionalProperties: false
          title: Resources
          description: ''
      required:
      - environment_name
      - branch_from
      - restore_code
      - restore_resources
      - resources
      additionalProperties: false
    Backup:
      type: object
      properties:
        id:
          type: string
          title: Backup Identifier
          description: The identifier of Backup
        created_at:
          type:
          - string
          - 'null'
          format: date-time
          title: Creation date
          description: The creation date
        updated_at:
          type:
          - string
          - 'null'
          format: date-time
          title: Update date
          description: The update date
        attributes:
          type: object
          additionalProperties:
            type: string
          title: Arbitrary attributes
          description: Arbitrary attributes attached to this resource
        status:
          type: string
          enum:
          - CREATED
          - DELETING
          title: Status
          description: The status of the backup
        expires_at:
          type:
          - string
          - 'null'
          format: date-time
          title: Expires At
          description: Expiration date of the backup
        index:
          type:
          - integer
          - 'null'
          title: Index
          description: The index of this automated backup
        commit_id:
          type: string
          title: Commit ID
          description: The ID of the code commit attached to the backup
        environment:
          type: string
          title: Environment
          description: The environment the backup belongs to
        safe:
          type: boolean
          title: Safe
          description: Whether this backup was taken in a safe way
        size_of_volumes:
          type:
          - integer
          - 'null'
          title: Size of volumes
          description: Total size of volumes backed up
        size_used:
          type:
          - integer
          - 'null'
          title: Size used
          description: Total size of space used on volumes backed up
        deployment:
          type:
          - string
          - 'null'
          title: Deployment
          description: The current deployment at the time of backup
        restorable:
          type: boolean
          title: Is restorable
          description: Whether the backup is restorable
        automated:
          type: boolean
          title: Is automated
          description: Whether the backup is automated
      required:
      - id
      - created_at
      - updated_at
      - attributes
      - status
      - expires_at
      - index
      - commit_id
      - environment
      - safe
      - size_of_volumes
      - size_used
      - deployment
      - restorable
      - automated
      additionalProperties: false
    EnvironmentBackupInput:
      type: object
      properties:
        safe:
          type: boolean
          title: Safe or live backup
          description: Take a safe or a live backup
      required:
      - safe
      additionalProperties: false
    BackupCollection:
      type: array
      items:
        $ref: '#/components/schemas/Backup'
    AcceptedResponse:
      type: object
      properties:
        status:
          type: string
          title: Status text
          description: The status text of the response
        code:
          type: integer
          title: Status code
          description: The status code of the response
      required:
      - status
      - code
      additionalProperties: false
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: https://auth.api.platform.sh/oauth2/token
          scopes: {}
          authorizationUrl: https://auth.api.platform.sh/oauth2/authorize
      description: ''
    OAuth2Admin:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: ''
          scopes:
            admin: administrative operations
      description: ''
x-tagGroups:
- name: Organization Administration
  tags:
  - Organizations
  - Organization Members
  - Organization Invitations
  - Organization Projects
  - Add-ons
- name: Project Administration
  tags:
  - Project
  - Domain Management
  - Cert Management
  - Certificate Provisioner
  - Project Variables
  - Repository
  - Third-Party Integrations
  - Support
- name: Environments
  tags:
  - Environment
  - Environment Backups
  - Environment Type
  - Environment Variables
  - Routing
  - Source Operations
  - Runtime Operations
  - Deployment
  - Autoscaling
- name: User Activity
  tags:
  - Project Activity
  - Environment Activity
- name: Project Access
  tags:
  - Project Invitations
  - Teams
  - Team Access
  - User Access
- name: Account Management
  tags:
  - API Tokens
  - Connections
  - MFA
  - Users
  - User Profiles
  - SSH Keys
  - Plans
- name: Billing
  tags:
  - Organization Management
  - Subscriptions
  - Orders
  - Invoices
  - Discounts
  - Vouchers
  - Records
  - Profiles
- name: Global Info
  tags:
  - Project Discovery
  - References
  - Regions
- name: Internal APIs
  tags:
  - Project Settings
  - Environment Settings
  - Deployment Target
  - System Information
  - Container Profile
