openapi: 3.2.0
info:
  title: Upsun.com Rest User Access API
  version: '1.0'
  contact:
    name: Support
    url: https://upsun.com/contact-us/
  termsOfService: https://upsun.com/trust-center/legal/tos/
  description: '# Introduction


    Upsun, formerly Platform.sh, is a container-based Platform-as-a-Service.'
  x-logo:
    url: https://docs.upsun.com/images/upsun-api.svg
    href: https://upsun.com/#section/Introduction
    altText: Upsun logo
servers:
- url: '{schemes}://api.upsun.com'
  description: The Upsun.com API gateway
  variables:
    schemes:
      default: https
security:
- OAuth2: []
tags:
- name: User Access
paths:
  /projects/{project_id}/user-access:
    parameters:
    - $ref: '#/components/parameters/ProjectID'
    get:
      summary: List user access for a project
      description: Returns a list of items representing the project access.
      operationId: list-project-user-access
      tags:
      - User Access
      parameters:
      - in: query
        name: page[size]
        description: Determines the number of items to show.
        schema:
          type: integer
          minimum: 1
          maximum: 200
          default: null
      - in: query
        name: page[before]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: page[after]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: sort
        description: 'Allows sorting by a single field.<br>

          Use a dash ("-") to sort descending.<br>

          Supported fields: `granted_at`, `updated_at`.

          '
        schema:
          type: string
          example: -updated_at
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserProjectAccess'
                  _links:
                    $ref: '#/components/schemas/ListLinks'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Grant user access to a project
      description: Grants one or more users access to a specific project.
      operationId: grant-project-user-access
      tags:
      - User Access
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ID of the user.
                  permissions:
                    $ref: '#/components/schemas/ProjectPermissions'
                  auto_add_member:
                    type: boolean
                    description: If the specified user is not a member of the project's organization, add it automatically.
                required:
                - user_id
                - permissions
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /projects/{project_id}/user-access/{user_id}:
    parameters:
    - $ref: '#/components/parameters/ProjectID'
    - $ref: '#/components/parameters/UserID'
    get:
      summary: Get user access for a project
      description: Retrieves the user's permissions for the current project.
      operationId: get-project-user-access
      tags:
      - User Access
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProjectAccess'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update user access for a project
      description: Updates the user's permissions for the current project.
      operationId: update-project-user-access
      tags:
      - User Access
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - permissions
              properties:
                permissions:
                  $ref: '#/components/schemas/ProjectPermissions'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Remove user access for a project
      description: Removes the user from the current project.
      operationId: remove-project-user-access
      tags:
      - User Access
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{user_id}/project-access:
    parameters:
    - $ref: '#/components/parameters/UserID'
    get:
      summary: List project access for a user
      description: Returns a list of items representing the user's project access.
      operationId: list-user-project-access
      tags:
      - User Access
      parameters:
      - in: query
        name: filter[organization_id]
        description: Allows filtering by `organization_id`.
        schema:
          type: string
      - in: query
        name: page[size]
        description: Determines the number of items to show.
        schema:
          type: integer
          minimum: 1
          maximum: 200
          default: null
      - in: query
        name: page[before]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: page[after]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: sort
        description: 'Allows sorting by a single field.<br>

          Use a dash ("-") to sort descending.<br>

          Supported fields: `project_title`, `granted_at`, `updated_at`.

          '
        schema:
          type: string
          example: -updated_at
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserProjectAccess'
                  _links:
                    $ref: '#/components/schemas/ListLinks'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Grant project access to a user
      description: Adds the user to one or more specified projects.
      operationId: grant-user-project-access
      tags:
      - User Access
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  project_id:
                    type: string
                    description: ID of the project.
                  permissions:
                    $ref: '#/components/schemas/ProjectPermissions'
                required:
                - project_id
                - permissions
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{user_id}/project-access/{project_id}:
    parameters:
    - $ref: '#/components/parameters/UserID'
    - $ref: '#/components/parameters/ProjectID'
    get:
      summary: Get project access for a user
      description: Retrieves the user's permissions for the current project.
      operationId: get-user-project-access
      tags:
      - User Access
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProjectAccess'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update project access for a user
      description: Updates the user's permissions for the current project.
      operationId: update-user-project-access
      tags:
      - User Access
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - permissions
              properties:
                permissions:
                  $ref: '#/components/schemas/ProjectPermissions'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Remove project access for a user
      description: Removes the user from the current project.
      operationId: remove-user-project-access
      tags:
      - User Access
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ProjectPermissions:
      type: array
      description: An array of project permissions.
      items:
        type: string
        enum:
        - admin
        - viewer
        - development:admin
        - development:contributor
        - development:viewer
        - staging:admin
        - staging:contributor
        - staging:viewer
        - production:admin
        - production:contributor
        - production:viewer
    Error:
      description: ''
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        code:
          type: number
        detail:
          type: object
        title:
          type: string
      title: ''
      x-examples:
        example-1:
          status: Invalid input
          message: This field is required.
          code: 400
          detail:
            field:
            - This field is required.
          title: Bad Request
    Link:
      type: object
      title: Link
      description: A hypermedia link to the {current, next, previous} set of items.
      properties:
        href:
          type: string
          description: URL of the link
    ListLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Link'
        previous:
          $ref: '#/components/schemas/Link'
        next:
          $ref: '#/components/schemas/Link'
    UserProjectAccess:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          description: The ID of the user.
        organization_id:
          type: string
          format: ulid
          description: The ID of the organization.
        project_id:
          type: string
          description: The ID of the project.
        project_title:
          type: string
          description: The title of the project.
        permissions:
          $ref: '#/components/schemas/ProjectPermissions'
        granted_at:
          type: string
          format: date-time
          description: The date and time when the access was granted.
        updated_at:
          type: string
          format: date-time
          description: The date and time when the access was last updated.
        _links:
          type: object
          properties:
            self:
              type: object
              description: Link to the current access item.
              properties:
                href:
                  type: string
                  description: URL of the link.
            update:
              type: object
              description: Link for updating the current access item.
              properties:
                href:
                  type: string
                  description: URL of the link.
                method:
                  type: string
                  description: The HTTP method to use.
            delete:
              type: object
              description: Link for deleting the current access item.
              properties:
                href:
                  type: string
                  description: URL of the link.
                method:
                  type: string
                  description: The HTTP method to use.
  parameters:
    ProjectID:
      name: project_id
      in: path
      required: true
      description: The ID of the project.
      schema:
        type: string
    UserID:
      name: user_id
      in: path
      required: true
      description: The ID of the user.
      schema:
        type: string
        example: d81c8ee2-44b3-429f-b944-a33ad7437690
        format: uuid
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: https://auth.api.platform.sh/oauth2/token
          scopes: {}
          authorizationUrl: https://auth.api.platform.sh/oauth2/authorize
      description: ''
    OAuth2Admin:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: ''
          scopes:
            admin: administrative operations
      description: ''
x-tagGroups:
- name: Organization Administration
  tags:
  - Organizations
  - Organization Members
  - Organization Invitations
  - Organization Projects
  - Add-ons
- name: Project Administration
  tags:
  - Project
  - Domain Management
  - Cert Management
  - Certificate Provisioner
  - Project Variables
  - Repository
  - Third-Party Integrations
  - Support
- name: Environments
  tags:
  - Environment
  - Environment Backups
  - Environment Type
  - Environment Variables
  - Routing
  - Source Operations
  - Runtime Operations
  - Deployment
  - Autoscaling
- name: User Activity
  tags:
  - Project Activity
  - Environment Activity
- name: Project Access
  tags:
  - Project Invitations
  - Teams
  - Team Access
  - User Access
- name: Account Management
  tags:
  - API Tokens
  - Connections
  - MFA
  - Users
  - User Profiles
  - SSH Keys
  - Plans
- name: Billing
  tags:
  - Organization Management
  - Subscriptions
  - Orders
  - Invoices
  - Discounts
  - Vouchers
  - Records
  - Profiles
- name: Global Info
  tags:
  - Project Discovery
  - References
  - Regions
- name: Internal APIs
  tags:
  - Project Settings
  - Environment Settings
  - Deployment Target
  - System Information
  - Container Profile
