openapi: 3.2.0
info:
  title: Upsun.com Rest Discounts API
  version: '1.0'
  contact:
    name: Support
    url: https://upsun.com/contact-us/
  termsOfService: https://upsun.com/trust-center/legal/tos/
  description: '# Introduction


    Upsun, formerly Platform.sh, is a container-based Platform-as-a-Service.'
  x-logo:
    url: https://docs.upsun.com/images/upsun-api.svg
    href: https://upsun.com/#section/Introduction
    altText: Upsun logo
servers:
- url: '{schemes}://api.upsun.com'
  description: The Upsun.com API gateway
  variables:
    schemes:
      default: https
security:
- OAuth2: []
tags:
- name: Discounts
paths:
  /discounts/{id}:
    get:
      tags:
      - Discounts
      summary: Get an organization discount
      operationId: get-discount
      parameters:
      - $ref: '#/components/parameters/discountId'
      responses:
        '200':
          description: A discount object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Discount'
      x-vendor: upsun
  /discounts/types/allowance:
    get:
      tags:
      - Discounts
      summary: Get the value of the First Project Incentive discount
      operationId: get-type-allowance
      responses:
        '200':
          description: A discount object
          content:
            application/json:
              schema:
                properties:
                  currencies:
                    description: Discount values per currency.
                    properties:
                      EUR:
                        description: Discount value in EUR.
                        properties:
                          formatted:
                            description: The discount amount formatted.
                            type: string
                          amount:
                            description: The discount amount.
                            type: number
                            format: float
                          currency:
                            description: The currency.
                            type: string
                          currency_symbol:
                            description: Currency symbol.
                            type: string
                        type: object
                      USD:
                        description: Discount value in USD.
                        properties:
                          formatted:
                            description: The discount amount formatted.
                            type: string
                          amount:
                            description: The discount amount.
                            type: number
                            format: float
                          currency:
                            description: The currency.
                            type: string
                          currency_symbol:
                            description: Currency symbol.
                            type: string
                        type: object
                      GBP:
                        description: Discount value in GBP.
                        properties:
                          formatted:
                            description: The discount amount formatted.
                            type: string
                          amount:
                            description: The discount amount.
                            type: number
                            format: float
                          currency:
                            description: The currency.
                            type: string
                          currency_symbol:
                            description: Currency symbol.
                            type: string
                        type: object
                      AUD:
                        description: Discount value in AUD.
                        properties:
                          formatted:
                            description: The discount amount formatted.
                            type: string
                          amount:
                            description: The discount amount.
                            type: number
                            format: float
                          currency:
                            description: The currency.
                            type: string
                          currency_symbol:
                            description: Currency symbol.
                            type: string
                        type: object
                      CAD:
                        description: Discount value in CAD.
                        properties:
                          formatted:
                            description: The discount amount formatted.
                            type: string
                          amount:
                            description: The discount amount.
                            type: number
                            format: float
                          currency:
                            description: The currency.
                            type: string
                          currency_symbol:
                            description: Currency symbol.
                            type: string
                        type: object
                    type: object
                type: object
      x-vendor: upsun
  /organizations/{organization_id}/discounts:
    get:
      summary: List organization discounts
      description: Retrieves all applicable discounts granted to the specified organization.
      operationId: list-org-discounts
      tags:
      - Discounts
      parameters:
      - $ref: '#/components/parameters/OrganizationIDName'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Discount'
                  _links:
                    $ref: '#/components/schemas/ListLinks'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
      x-vendor: upsun
components:
  parameters:
    OrganizationIDName:
      in: path
      name: organization_id
      description: 'The ID of the organization.<br>

        Prefix with name= to retrieve the organization by name instead.

        '
      required: true
      schema:
        type: string
    discountId:
      name: id
      in: path
      description: The ID of the organization discount
      required: true
      schema:
        type: string
  schemas:
    CurrencyAmount:
      description: Currency amount with detailed components.
      properties:
        formatted:
          description: Formatted currency value.
          type: string
        amount:
          description: Plain amount.
          type: number
          format: float
        currency_code:
          description: Currency code.
          type: string
        currency_symbol:
          description: Currency symbol.
          type: string
      type: object
    Error:
      description: ''
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        code:
          type: number
        detail:
          type: object
        title:
          type: string
      title: ''
      x-examples:
        example-1:
          status: Invalid input
          message: This field is required.
          code: 400
          detail:
            field:
            - This field is required.
          title: Bad Request
    Discount:
      description: The discount object.
      properties:
        id:
          description: The ID of the organization discount.
          type: integer
        organization_id:
          description: The ULID of the organization the discount applies to.
          type: string
        type:
          description: The machine name of the discount type.
          type: string
          enum:
          - allowance
          - startup
          - enterprise
        type_label:
          description: The label of the discount type.
          type: string
        status:
          description: The status of the discount.
          type: string
          enum:
          - inactive
          - active
          - expired
          - deactivated
        commitment:
          description: The minimum commitment associated with the discount (if applicable).
          properties:
            months:
              description: Commitment period length in months.
              type: integer
            amount:
              description: Commitment amounts.
              properties:
                monthly:
                  $ref: '#/components/schemas/CurrencyAmount'
                commitment_period:
                  $ref: '#/components/schemas/CurrencyAmount'
                contract_total:
                  $ref: '#/components/schemas/CurrencyAmount'
              type: object
            net:
              description: Net commitment amounts (discount deducted).
              properties:
                monthly:
                  $ref: '#/components/schemas/CurrencyAmount'
                commitment_period:
                  $ref: '#/components/schemas/CurrencyAmount'
                contract_total:
                  $ref: '#/components/schemas/CurrencyAmount'
              type: object
          type:
          - object
          - 'null'
        total_months:
          description: The contract length in months (if applicable).
          type:
          - integer
          - 'null'
        discount:
          description: Discount value per relevant time periods.
          properties:
            monthly:
              $ref: '#/components/schemas/CurrencyAmount'
            commitment_period:
              $ref: '#/components/schemas/CurrencyAmountNullable'
            contract_total:
              $ref: '#/components/schemas/CurrencyAmountNullable'
          type: object
        config:
          description: The discount type specific configuration.
          type: object
        start_at:
          description: The start time of the discount period.
          type: string
          format: date-time
        end_at:
          description: The end time of the discount period (if applicable).
          type:
          - string
          - 'null'
          format: date-time
      type: object
    Link:
      type: object
      title: Link
      description: A hypermedia link to the {current, next, previous} set of items.
      properties:
        href:
          type: string
          description: URL of the link
    CurrencyAmountNullable:
      description: Currency amount with detailed components.
      properties:
        formatted:
          description: Formatted currency value.
          type: string
        amount:
          description: Plain amount.
          type: number
          format: float
        currency_code:
          description: Currency code.
          type: string
        currency_symbol:
          description: Currency symbol.
          type: string
      type:
      - object
      - 'null'
    ListLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Link'
        previous:
          $ref: '#/components/schemas/Link'
        next:
          $ref: '#/components/schemas/Link'
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: https://auth.api.platform.sh/oauth2/token
          scopes: {}
          authorizationUrl: https://auth.api.platform.sh/oauth2/authorize
      description: ''
    OAuth2Admin:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: ''
          scopes:
            admin: administrative operations
      description: ''
x-tagGroups:
- name: Organization Administration
  tags:
  - Organizations
  - Organization Members
  - Organization Invitations
  - Organization Projects
  - Add-ons
- name: Project Administration
  tags:
  - Project
  - Domain Management
  - Cert Management
  - Certificate Provisioner
  - Project Variables
  - Repository
  - Third-Party Integrations
  - Support
- name: Environments
  tags:
  - Environment
  - Environment Backups
  - Environment Type
  - Environment Variables
  - Routing
  - Source Operations
  - Runtime Operations
  - Deployment
  - Autoscaling
- name: User Activity
  tags:
  - Project Activity
  - Environment Activity
- name: Project Access
  tags:
  - Project Invitations
  - Teams
  - Team Access
  - User Access
- name: Account Management
  tags:
  - API Tokens
  - Connections
  - MFA
  - Users
  - User Profiles
  - SSH Keys
  - Plans
- name: Billing
  tags:
  - Organization Management
  - Subscriptions
  - Orders
  - Invoices
  - Discounts
  - Vouchers
  - Records
  - Profiles
- name: Global Info
  tags:
  - Project Discovery
  - References
  - Regions
- name: Internal APIs
  tags:
  - Project Settings
  - Environment Settings
  - Deployment Target
  - System Information
  - Container Profile
