openapi: 3.2.0
info:
  title: Upsun.com Rest Regions API
  version: '1.0'
  contact:
    name: Support
    url: https://upsun.com/contact-us/
  termsOfService: https://upsun.com/trust-center/legal/tos/
  description: '# Introduction


    Upsun, formerly Platform.sh, is a container-based Platform-as-a-Service.'
  x-logo:
    url: https://docs.upsun.com/images/upsun-api.svg
    href: https://upsun.com/#section/Introduction
    altText: Upsun logo
servers:
- url: '{schemes}://api.upsun.com'
  description: The Upsun.com API gateway
  variables:
    schemes:
      default: https
security:
- OAuth2: []
tags:
- name: Regions
paths:
  /regions:
    get:
      summary: List regions
      description: Retrieves a list of available regions.
      operationId: list-regions
      tags:
      - Regions
      parameters:
      - in: query
        name: filter[available]
        description: Allows filtering by `available` using one or more operators.
        style: deepObject
        explode: true
        schema:
          $ref: '#/components/schemas/StringFilter'
      - in: query
        name: filter[private]
        description: Allows filtering by `private` using one or more operators.
        style: deepObject
        explode: true
        schema:
          $ref: '#/components/schemas/StringFilter'
      - in: query
        name: filter[zone]
        description: Allows filtering by `zone` using one or more operators.
        style: deepObject
        explode: true
        schema:
          $ref: '#/components/schemas/StringFilter'
      - in: query
        name: page[size]
        description: Determines the number of items to show.
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: null
      - in: query
        name: page[before]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: page[after]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: sort
        description: 'Allows sorting by a single field.<br>

          Use a dash ("-") to sort descending.<br>

          Supported fields: `id`, `created_at`, `updated_at`.

          '
        schema:
          type: string
          example: -updated_at
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  regions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Region'
                  _links:
                    $ref: '#/components/schemas/ListLinks'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /regions/{region_id}:
    get:
      summary: Get region
      description: Retrieves the specified region.
      operationId: get-region
      tags:
      - Regions
      parameters:
      - $ref: '#/components/parameters/RegionID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    RegionID:
      in: path
      name: region_id
      description: The ID of the region.
      required: true
      schema:
        type: string
  schemas:
    Error:
      description: ''
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        code:
          type: number
        detail:
          type: object
        title:
          type: string
      title: ''
      x-examples:
        example-1:
          status: Invalid input
          message: This field is required.
          code: 400
          detail:
            field:
            - This field is required.
          title: Bad Request
    StringFilter:
      type: object
      properties:
        eq:
          type: string
          description: Equal
        ne:
          type: string
          description: Not equal
        in:
          type: string
          description: In (comma-separated list)
        nin:
          type: string
          description: Not in (comma-separated list)
        between:
          type: string
          description: Between (comma-separated list)
        contains:
          type: string
          description: Contains
        starts:
          type: string
          description: Starts with
        ends:
          type: string
          description: Ends with
    Link:
      type: object
      title: Link
      description: A hypermedia link to the {current, next, previous} set of items.
      properties:
        href:
          type: string
          description: URL of the link
    ListLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Link'
        previous:
          $ref: '#/components/schemas/Link'
        next:
          $ref: '#/components/schemas/Link'
    Region:
      description: The hosting region.
      properties:
        id:
          description: The ID of the region.
          type: string
        label:
          description: The human-readable name of the region.
          type: string
        zone:
          description: Geographical zone of the region
          type: string
        selection_label:
          description: The label to display when choosing between regions for new projects.
          type: string
        project_label:
          description: The label to display on existing projects.
          type: string
        timezone:
          description: Default timezone of the region
          type: string
        available:
          description: Indicator whether or not this region is selectable during the checkout. Not available regions will never show up during checkout.
          type: boolean
        private:
          description: Indicator whether or not this platform is for private use only.
          type: boolean
        endpoint:
          description: Link to the region API endpoint.
          type: string
        provider:
          description: Information about the region provider.
          properties:
            name:
              type: string
            logo:
              type: string
          type: object
        datacenter:
          description: Information about the region provider data center.
          properties:
            name:
              type: string
            label:
              type: string
            location:
              type: string
          type: object
        environmental_impact:
          description: Information about the region provider's environmental impact.
          properties:
            zone:
              type: string
            carbon_intensity:
              type: string
            green:
              type: boolean
          type: object
      type: object
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: https://auth.api.platform.sh/oauth2/token
          scopes: {}
          authorizationUrl: https://auth.api.platform.sh/oauth2/authorize
      description: ''
    OAuth2Admin:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: ''
          scopes:
            admin: administrative operations
      description: ''
x-tagGroups:
- name: Organization Administration
  tags:
  - Organizations
  - Organization Members
  - Organization Invitations
  - Organization Projects
  - Add-ons
- name: Project Administration
  tags:
  - Project
  - Domain Management
  - Cert Management
  - Certificate Provisioner
  - Project Variables
  - Repository
  - Third-Party Integrations
  - Support
- name: Environments
  tags:
  - Environment
  - Environment Backups
  - Environment Type
  - Environment Variables
  - Routing
  - Source Operations
  - Runtime Operations
  - Deployment
  - Autoscaling
- name: User Activity
  tags:
  - Project Activity
  - Environment Activity
- name: Project Access
  tags:
  - Project Invitations
  - Teams
  - Team Access
  - User Access
- name: Account Management
  tags:
  - API Tokens
  - Connections
  - MFA
  - Users
  - User Profiles
  - SSH Keys
  - Plans
- name: Billing
  tags:
  - Organization Management
  - Subscriptions
  - Orders
  - Invoices
  - Discounts
  - Vouchers
  - Records
  - Profiles
- name: Global Info
  tags:
  - Project Discovery
  - References
  - Regions
- name: Internal APIs
  tags:
  - Project Settings
  - Environment Settings
  - Deployment Target
  - System Information
  - Container Profile
