openapi: 3.2.0
info:
  title: Upsun.com Rest Organization Invitations API
  version: '1.0'
  contact:
    name: Support
    url: https://upsun.com/contact-us/
  termsOfService: https://upsun.com/trust-center/legal/tos/
  description: '# Introduction


    Upsun, formerly Platform.sh, is a container-based Platform-as-a-Service.'
  x-logo:
    url: https://docs.upsun.com/images/upsun-api.svg
    href: https://upsun.com/#section/Introduction
    altText: Upsun logo
servers:
- url: '{schemes}://api.upsun.com'
  description: The Upsun.com API gateway
  variables:
    schemes:
      default: https
security:
- OAuth2: []
tags:
- name: Organization Invitations
paths:
  /organizations/{organization_id}/invitations:
    parameters:
    - $ref: '#/components/parameters/OrganizationID'
    post:
      summary: Invite user to an organization by email
      description: Creates an invitation to an organization for a user with the specified email address.
      operationId: create-org-invite
      tags:
      - Organization Invitations
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationInvitation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict when there already is a pending invitation for the invitee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the invitee.
                permissions:
                  $ref: '#/components/schemas/OrganizationPermissions'
                force:
                  type: boolean
                  description: Whether to cancel any pending invitation for the specified invitee, and create a new invitation.
              required:
              - email
              - permissions
    get:
      summary: List invitations to an organization
      description: Returns a list of invitations to an organization.
      operationId: list-org-invites
      tags:
      - Organization Invitations
      parameters:
      - in: query
        name: filter[state]
        description: 'Allows filtering by `state` of the invtations: "pending" (default), "error".'
        style: deepObject
        explode: true
        schema:
          $ref: '#/components/schemas/StringFilter'
      - in: query
        name: page[size]
        description: Determines the number of items to show.
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: null
      - in: query
        name: page[before]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: page[after]
        description: Pagination cursor. This is automatically generated as necessary and provided in HAL links (_links); it should not be constructed externally.
        schema:
          type: string
      - in: query
        name: sort
        description: 'Allows sorting by a single field.<br>

          Use a dash ("-") to sort descending.

          '
        schema:
          type: string
          enum:
          - updated_at
          - -updated_at
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationInvitation'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /organizations/{organization_id}/invitations/{invitation_id}:
    parameters:
    - $ref: '#/components/parameters/OrganizationID'
    - $ref: '#/components/parameters/InvitationID'
    delete:
      summary: Cancel a pending invitation to an organization
      description: Cancels the specified invitation.
      operationId: cancel-org-invite
      tags:
      - Organization Invitations
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
components:
  schemas:
    OrganizationPermissions:
      type: array
      description: The permissions the invitee should be given on the organization.
      items:
        type: string
        enum:
        - admin
        - billing
        - plans
        - members
        - project:create
        - projects:list
    Error:
      description: ''
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        code:
          type: number
        detail:
          type: object
        title:
          type: string
      title: ''
      x-examples:
        example-1:
          status: Invalid input
          message: This field is required.
          code: 400
          detail:
            field:
            - This field is required.
          title: Bad Request
    StringFilter:
      type: object
      properties:
        eq:
          type: string
          description: Equal
        ne:
          type: string
          description: Not equal
        in:
          type: string
          description: In (comma-separated list)
        nin:
          type: string
          description: Not in (comma-separated list)
        between:
          type: string
          description: Between (comma-separated list)
        contains:
          type: string
          description: Contains
        starts:
          type: string
          description: Starts with
        ends:
          type: string
          description: Ends with
    OrganizationInvitation:
      title: OrganizationInvitation
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the invitation.
        state:
          type: string
          enum:
          - pending
          - processing
          - accepted
          - cancelled
          - error
          description: The invitation state.
        organization_id:
          type: string
          description: The ID of the organization.
        email:
          type: string
          format: email
          description: The email address of the invitee.
        owner:
          type: object
          description: The inviter.
          properties:
            id:
              type: string
              format: uuid
              description: The ID of the user.
            display_name:
              type: string
              description: The user's display name.
        created_at:
          type: string
          description: The date and time when the invitation was created.
          format: date-time
        updated_at:
          type: string
          format: date-time
          description: The date and time when the invitation was last updated.
        finished_at:
          type:
          - string
          - 'null'
          format: date-time
          description: The date and time when the invitation was finished.
        permissions:
          $ref: '#/components/schemas/OrganizationPermissions'
      x-examples:
        example-1:
          id: 97f46eca-6276-4993-bfeb-bbb53cba6f08
          state: pending
          organization_id: 01ARZ3NDEKTSV4RRFFQ69G5FAV
          email: bob@example.com
          owner:
            id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            display_name: Alice
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
          finished_at: null
          permissions:
          - members
  parameters:
    InvitationID:
      name: invitation_id
      in: path
      required: true
      description: The ID of the invitation.
      schema:
        type: string
    OrganizationID:
      name: organization_id
      in: path
      required: true
      description: The ID of the organization.
      schema:
        type: string
        format: ulid
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: https://auth.api.platform.sh/oauth2/token
          scopes: {}
          authorizationUrl: https://auth.api.platform.sh/oauth2/authorize
      description: ''
    OAuth2Admin:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.api.platform.sh/oauth2/token
          refreshUrl: ''
          scopes:
            admin: administrative operations
      description: ''
x-tagGroups:
- name: Organization Administration
  tags:
  - Organizations
  - Organization Members
  - Organization Invitations
  - Organization Projects
  - Add-ons
- name: Project Administration
  tags:
  - Project
  - Domain Management
  - Cert Management
  - Certificate Provisioner
  - Project Variables
  - Repository
  - Third-Party Integrations
  - Support
- name: Environments
  tags:
  - Environment
  - Environment Backups
  - Environment Type
  - Environment Variables
  - Routing
  - Source Operations
  - Runtime Operations
  - Deployment
  - Autoscaling
- name: User Activity
  tags:
  - Project Activity
  - Environment Activity
- name: Project Access
  tags:
  - Project Invitations
  - Teams
  - Team Access
  - User Access
- name: Account Management
  tags:
  - API Tokens
  - Connections
  - MFA
  - Users
  - User Profiles
  - SSH Keys
  - Plans
- name: Billing
  tags:
  - Organization Management
  - Subscriptions
  - Orders
  - Invoices
  - Discounts
  - Vouchers
  - Records
  - Profiles
- name: Global Info
  tags:
  - Project Discovery
  - References
  - Regions
- name: Internal APIs
  tags:
  - Project Settings
  - Environment Settings
  - Deployment Target
  - System Information
  - Container Profile
